/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  '🚩site': [
    'README',
    {
      type: "category",
      label: "搭建知识库",
      collapsed: false,
      items: [
        'site/about-build',
        'site/about-deploy',
        'site/about-theme',
        'site/about-write',
      ],
    }
  ],

  'life': [
    {
      type: 'category',
      label: "🎮 就知道玩",
      link: {
        type: 'generated-index',
        slug: '/category/just-paly',
      },
      collapsed: true,
      items: [
        'life/play/go-out-and-play',
        {
          type: "category",
          label: 'LEGO',
          collapsed: true,
          items: [
            'life/play/LEGO/koenigsegg-76900',
          ],
        }
      ],
    },
    {
      type: 'category',
      label: "🍻 就知道吃",
      link: {
        type: 'generated-index',
        slug: '/category/just-eat',
      },
      collapsed: true,
      items: [
        'life/foods/always-eating',
      ],
    },
  ],
};

module.exports = sidebars;
